import WelcomeContainer from '@/src/component/UI/WelcomeContainer';
import { Box } from '@mui/material';
import type { Metadata } from 'next';
import { Toaster } from 'react-hot-toast';
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            style: {
              background: '#000',
              color: '#fff',
              borderRadius: '10px',
            },
          }}
        />
        {/* <Box className="flex bg-light-purpleBackground dark:bg-dark-background w-full min-h-[100vh]"> */}
        {children}
        {/* </Box> */}
      </body>
    </html>
  );
}
 
