import type { Metadata } from 'next';
import ClientRootLayout from '../component/UI/layouts/RootLayout';
import 'react-tabs/style/react-tabs.css';
import './globals.scss';
import { Toaster } from "react-hot-toast";
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="Description of your web app" />
        <link rel="manifest" href="/manifest.webmanifest" />

      </head>
      <body>
        <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            style: {
              background: "#000",
              color: "#fff",
              borderRadius: "10px",
            },
          }}
        />
        <ClientRootLayout>{children}</ClientRootLayout>
      </body>
    </html>
  );
}
